# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# It starts from the rabbitmq base image.
FROM rabbitmq:3-management

# Add Maintainer Info.
LABEL maintainer="Ícaro Ribeiro <icaroribeiro@hotmail.com>"